# Generated by Django 3.0.11 on 2021-03-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('ceo', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
